name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Fetch git tags
        run: git fetch --unshallow --tags

      - name: Generate changelog
        run: bash <(curl -fsSL https://raw.githubusercontent.com/neogeek/generate-local-changelog/v1.0.3/bin/generate-local-changelog) --unreleased > CHANGELOG.md

      - name: Setup git
        run: |
          git config user.name "neogeek-bot"
          git config user.email "neogeek0101+bot@gmail.com"

      - name: Git commit changes
        run: |
          git add CHANGELOG.md
          git commit -m "Updated CHANGELOG.md [skip ci]" || exit 0
          git push origin main
