name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12.20.0, 14.13.1, 16.0.0]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Update NPM to latest
        run: npm install npm@latest -g

      - name: Print Node.js and NPM version
        run: |
          node -v
          npm -v

      - name: Check for ".only" tests
        run: |
          find src -name '*.test.ts' -exec grep ".only" {} \;
          if [ ! -z "$(find src -name '*.test.ts' -exec grep ".only" {} \;)" ]; then exit 1; fi

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        timeout-minutes: 5
        run: npm test
